server:
  port: 8090
spring:
  aop: 
    auto: true
  rabbitmq:
    host: ${rmq.asso.host}
    virtual-host: ${rmq.asso.virtual-host}
    port: ${rmq.asso.port}
    username: ${rmq.asso.username}
    password: ${rmq.asso.password}
  datasource:
    driver-class-name: ${db.asso.driverclass}
    url: ${db.asso.url}
    username: ${db.asso.name}
    password: ${db.asso.pwd}
  resources:
    static-locations:
    - classpath:/static/html/
  redis:
    host: ${rd.asso.host}
    port: ${rd.asso.port}
mybatis:
  configuration:
    auto-mapping-behavior: full
  mapper-locations: classpath:/mapper/*Mapper.xml
logging:
  level:
    cn.songlin.mapper : debug
mytest: 
  name: zhangsan
  pwd: 123
zhangsan: hh
multi: 
  datasource:
    enable-dynamic: true  #开启多数据源动态配置
    custom: multi,community #自定义多数据源
    default: #默认配置，必配
      driverclass: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.20.100:3306/community?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
    multi: 
      driverclass: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.20.100:3306/multi?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
    community: 
      driverclass: ${db.asso.driverclass}
      url: ${db.asso.url}
      username: ${db.asso.name}
      password: root